### ISSUE TITLE
Plugin not working with Rhythmbox 2.99.1

### ISSUE THREAD

**Issue by silberzwiebel** [asermax/lastfm_extension#22]
Hello,

sorry to say, but your plugin is not working under Rhythmbox 2.99.1.
This is the error-output:

```
Traceback (most recent call last):
  File "/home/thomas/.local/share/rhythmbox/plugins/lastfm_extension/lastfm_extension.py", line 435, in do_activate
    self.uim = self.object.props.ui_manager
 AttributeError: 'gi._gobject.GProps' object has no attribute 'ui_manager'
```

Rhythmbox is crashing completely if I try to access the options.

Thanks for fixing it!

silberzwiebel

**Comment by asermax** [comment]
Blame upstream for that :3 
Is well known by now that Rhythmbox devs made quite some backward incompatible changes that broke practically every plugin out there.

Currently, I'm not being able to do much since the distro I use haven't updated to 2.99 yet (not that I really want to update either, I have heard some ugly stuff about it :/), so I need to build a testing env, and I don't have much time on my hands.
Neverthless, a fellow plugin dev is working on a compatibility module that should help most plugin devs make their plugins compatible with most 2.xx versions.
You can check the current development and discussion [here](https://github.com/fossfreedom/coverart-browser/issues/171).

Once that module is mature and I got my testing env up, I'll go onto fixing this issue. Feel free to take part of the development if you feel like it :]
